# App config
server:
  port: 8080

spring:
  application:
    name: blog-service
  data:
    mongodb:
      uri: database-url
      database: blog-project

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost